### ISSUE TITLE
Correct license links

### ISSUE THREAD

**Issue by Max1Truc** [mozilla-iot/example-adapter#21]
I'm probably wrong but license links seem broken.
In fact [this link](http://mozilla.org/MPL/2.0/.*) doesn't work while [this one](http://mozilla.org/MPL/2.0/) works.
(`http://mozilla.org/MPL/2.0/.*` ➡️ `http://mozilla.org/MPL/2.0/`)

**Comment by mrstegeman** [comment]
Where are the links, exactly?

**Comment by hobinjk** [comment]
https://github.com/mozilla-iot/example-adapter/blob/master/example-adapter.js#L6

The asterisk shouldn't be there but the period is just there because it's a sentence
